"""
Milvus collection setup utilities for docs-agent hybrid search.

Default behavior creates a single partitioned `docs_rag` collection, and helper
functions can also create non-partitioned collections for benchmark variants.
"""
import os
from pymilvus import MilvusClient, DataType, Function, FunctionType


COLLECTION_NAME = "docs_rag"
EMBEDDING_MODEL = "sentence-transformers/all-mpnet-base-v2"
EMBEDDING_DIM = 768


def create_schema(
    *,
    partition_key: bool = True,
    dense_dim: int = EMBEDDING_DIM,
    enable_bm25_function: bool = True,
):
    """Build the hybrid-search schema used by unified or split collections."""
    schema = MilvusClient.create_schema(
        enable_dynamic_fields=True,
        description="Unified docs RAG: docs + issues + code with hybrid search",
    )

    # Primary key
    schema.add_field(
        field_name="chunk_id",
        datatype=DataType.VARCHAR,
        max_length=128,
        is_primary=True,
        description="SHA256(file_unique_id + ':' + chunk_index)",
    )

    # Source identification
    schema.add_field(field_name="file_unique_id", datatype=DataType.VARCHAR, max_length=512)
    schema.add_field(field_name="repo_name", datatype=DataType.VARCHAR, max_length=256)
    schema.add_field(field_name="file_path", datatype=DataType.VARCHAR, max_length=512)
    schema.add_field(field_name="file_name", datatype=DataType.VARCHAR, max_length=256)
    schema.add_field(field_name="citation_url", datatype=DataType.VARCHAR, max_length=1024)
    schema.add_field(field_name="chunk_index", datatype=DataType.INT64)

    # Content — must have analyzer for BM25
    schema.add_field(
        field_name="content_text",
        datatype=DataType.VARCHAR,
        max_length=8000,
        enable_analyzer=True,
        enable_match=True,
        analyzer_params={
            "tokenizer": "standard",
            "filter": ["lowercase"],
        },
        description="Raw text chunk (docs, issues, or code with metadata header)",
    )

    # Source type is used for filtering and optional partition-key routing.
    schema.add_field(
        field_name="source_type",
        datatype=DataType.VARCHAR,
        max_length=64,
        is_partition_key=partition_key,
        description="docs | issues | code",
    )

    # Dense vector (semantic search)
    schema.add_field(
        field_name="dense_vector",
        datatype=DataType.FLOAT_VECTOR,
        dim=dense_dim,
        description="Dense embedding vector",
    )

    # Sparse vector (BM25 keyword search — auto-generated by Milvus)
    schema.add_field(
        field_name="sparse_vector",
        datatype=DataType.SPARSE_FLOAT_VECTOR,
        description="Auto-generated by Milvus BM25 function",
    )

    # Timestamp
    schema.add_field(field_name="last_updated", datatype=DataType.INT64)

    if enable_bm25_function:
        # BM25 function: content_text -> sparse_vector
        schema.add_function(Function(
            name="bm25_embedding",
            function_type=FunctionType.BM25,
            input_field_names=["content_text"],
            output_field_names=["sparse_vector"],
        ))

    return schema


def create_index_params():
    """Prepare index parameters for dense and sparse vector fields.

    Uses HNSW for dense_vector (required for partition key isolation).
    """
    index_params = MilvusClient.prepare_index_params()

    index_params.add_index(
        field_name="dense_vector",
        index_type="HNSW",
        metric_type="COSINE",
        params={"M": 16, "efConstruction": 200},
    )

    index_params.add_index(
        field_name="sparse_vector",
        index_type="SPARSE_INVERTED_INDEX",
        metric_type="BM25",
    )

    return index_params


def get_client():
    """Return a connected MilvusClient."""
    host = os.getenv("MILVUS_HOST", "my-release-milvus.docs-ag.svc.cluster.local")
    port = os.getenv("MILVUS_PORT", "19530")
    user = os.getenv("MILVUS_USER", "root")
    password = os.getenv("MILVUS_PASSWORD", "Milvus")
    return MilvusClient(uri=f"http://{host}:{port}", user=user, password=password)


def setup_collection(
    recreate: bool = False,
    *,
    collection_name: str = COLLECTION_NAME,
    partition_key: bool = True,
    dense_dim: int = EMBEDDING_DIM,
    enable_bm25_function: bool = True,
):
    """Create (or recreate) a hybrid-search collection."""
    client = get_client()

    if client.has_collection(collection_name):
        if recreate:
            print(f"[SETUP] Dropping existing collection: {collection_name}")
            client.drop_collection(collection_name)
        else:
            print(f"[SETUP] Collection '{collection_name}' already exists — skipping")
            return client

    schema = create_schema(
        partition_key=partition_key,
        dense_dim=dense_dim,
        enable_bm25_function=enable_bm25_function,
    )
    index_params = create_index_params()

    create_kwargs = {
        "collection_name": collection_name,
        "schema": schema,
        "index_params": index_params,
    }
    if partition_key:
        create_kwargs["properties"] = {"partitionkey.isolation": True}

    client.create_collection(**create_kwargs)

    if partition_key:
        print(f"[SETUP] Created collection: {collection_name} with partition key isolation")
    else:
        print(f"[SETUP] Created collection: {collection_name} (non-partitioned)")
    return client


if __name__ == "__main__":
    client = setup_collection(recreate=True, collection_name=COLLECTION_NAME, partition_key=True)
    collections = client.list_collections()
    print(f"[SETUP] Collections: {collections}")
